In [2]:
# Import the numpy package under the name `np`

In [3]:
import numpy as np

In [4]:
#  Print the numpy version and the configuration

In [9]:
np.version.version

AttributeError: module 'numpy' has no attribute 'show'

In [10]:
np.__version__



'1.16.5'

In [12]:
np.show_config()

mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Seinf/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/Seinf/Anaconda3\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Seinf/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/U

In [13]:
# Create a null vector of size 10

In [27]:
e = np.zeros((10))
e


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [28]:
# How to find the memory size of any array 

In [31]:
e.itemsize


8

In [32]:
# How to get the documentation of the numpy add function from the command line?

In [33]:
np.info

<function numpy.info(object=None, maxwidth=76, output=<ipykernel.iostream.OutStream object at 0x0000028831CEF688>, toplevel='numpy')>

In [34]:
# 6. Create a null vector of size 10 but the fifth value which is 1

In [40]:
a = np.zeros((10))
a[4]=1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [41]:
#  7. Create a vector with values ranging from 10 to 49 

In [43]:
a = np.arange(10,50,1)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [44]:
# 8. Reverse a vector (first element becomes last)

In [45]:
a[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [46]:
#  9. Create a 3x3 matrix with values ranging from 0 to 8

In [62]:
x =  np.arange(0, 9).reshape(3,3)
x


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [63]:
# 10. Find indices of non-zero elements from [1,2,0,0,4,0] 

In [73]:
a = [1,2,0,0,4,0] 
b= range(len(a))
for i in b:
    if a[i]!=0:
        print(i)
    else:
        continue
   

0
1
4


In [74]:
# 11. Create a 3x3 identity matrix 

In [75]:
f = np.eye(3)
f

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [76]:
# 12. Create a 3x3x3 array with random values

In [81]:
x=np.random.random((3,3))
x

array([[0.35931807, 0.04719468, 0.247175  ],
       [0.60016588, 0.72285452, 0.88234186],
       [0.46036064, 0.66441545, 0.28020451]])

In [82]:
# 13. Create a 10x10 array with random values and find the minimum and maximum values

In [90]:
x=np.random.random((10,10))
x


array([[0.85036355, 0.69703904, 0.23601558, 0.83798199, 0.3551097 ,
        0.15070661, 0.84260602, 0.76426799, 0.00245726, 0.73633643],
       [0.49607219, 0.3900652 , 0.2255587 , 0.13439672, 0.37125336,
        0.27211729, 0.44759389, 0.58954546, 0.6168391 , 0.27045044],
       [0.52130599, 0.12682148, 0.93261259, 0.94046383, 0.95066378,
        0.34253289, 0.7906712 , 0.72381714, 0.39306377, 0.57693382],
       [0.22205164, 0.77405156, 0.39629846, 0.24849185, 0.40270381,
        0.9256292 , 0.53473412, 0.96081683, 0.66491281, 0.93156119],
       [0.473804  , 0.34058088, 0.51420566, 0.03180092, 0.64083469,
        0.58995416, 0.36607908, 0.36589288, 0.95408107, 0.79766867],
       [0.18216285, 0.134913  , 0.06530653, 0.38405236, 0.35317724,
        0.53427001, 0.55274339, 0.90425476, 0.59745371, 0.91341601],
       [0.50851143, 0.84748793, 0.754738  , 0.33222716, 0.03864528,
        0.24544767, 0.07568283, 0.03758924, 0.05775178, 0.98119   ],
       [0.29659994, 0.06950341, 0.4650003

In [91]:
a=x.min()
a


0.002457255588974694

In [92]:
b=x.max()
b

0.9811899978454229

In [93]:
# 14. Create a random vector of size 30 and find the mean value

In [97]:
a = np.random.random(30)
a


array([0.61345387, 0.22099384, 0.67458108, 0.8400545 , 0.93794955,
       0.58382882, 0.80262571, 0.43032849, 0.37865217, 0.4723833 ,
       0.61276596, 0.2538561 , 0.32145772, 0.9132239 , 0.46621041,
       0.60346342, 0.60911036, 0.51918956, 0.49796123, 0.28149301,
       0.90456554, 0.41136226, 0.66567305, 0.54466559, 0.43005645,
       0.57689518, 0.91939899, 0.98544228, 0.2046841 , 0.91055314])

In [99]:
b = a.mean()
b


0.5862293192269673

In [100]:
# 15. Create a 2d array with 1 on the border and 0 inside

In [108]:
g =np.empty((3,4)) ???
g


SyntaxError: invalid syntax (<ipython-input-108-7d73e4f17b73>, line 1)

In [117]:
a = np.array([1:-1,  1:-1])
a

SyntaxError: invalid syntax (<ipython-input-117-b21de0feaad0>, line 1)

In [ ]:
# 11 Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (np.diag)

In [18]:
import numpy as np
f = np.diagflat([[1,2],[3,4]],-1)
f



array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [19]:
# 12. Normalize a 5x5 random matrix

In [44]:
a=np.random.randint(5, 45, size = (5,5))
a
amax, amin = a.max(), a.min()
a = (a - amin)/(amax - amin)
a


array([[1.        , 0.97297297, 0.59459459, 0.75675676, 0.21621622],
       [0.56756757, 0.37837838, 0.21621622, 0.75675676, 1.        ],
       [0.        , 0.97297297, 0.43243243, 0.43243243, 0.78378378],
       [0.2972973 , 0.81081081, 0.59459459, 0.54054054, 0.43243243],
       [0.37837838, 0.08108108, 0.56756757, 0.91891892, 0.        ]])

In [45]:
# 13. How to find common values between two arrays?

In [50]:
a = np.random.randint(1,20, size = (3,3))
a


array([[10,  4, 19],
       [ 9,  4,  4],
       [19, 10,  2]])

In [54]:
b = np.random.randint(1,20, size = (3,3))
b


array([[ 3, 12, 12],
       [ 5, 17,  7],
       [12,  2, 19]])

In [58]:
c = np.intersect1d(a,b)
c

array([ 2, 19])

In [59]:
# 14. Create a random vector of size 10 and sort it 

In [78]:
b = np.random.random(10)
b





array([0.61233977, 0.98847749, 0.95004641, 0.06668811, 0.71987879,
       0.83473805, 0.22803403, 0.00325085, 0.48046376, 0.51813503])

In [79]:
c=np.sort(b)
c

array([0.00325085, 0.06668811, 0.22803403, 0.48046376, 0.51813503,
       0.61233977, 0.71987879, 0.83473805, 0.95004641, 0.98847749])

In [100]:
# 15 Create random vector of size 10 and replace the maximum value by 0
rv = np.random.rand(10)

rr = max(rv)
rep=np.argmax(rv)
print(rep)
rv[rep]=0 
rv


4


array([0.36326204, 0.19669121, 0.43696928, 0.12073226, 0.        ,
       0.29522889, 0.65985699, 0.14869526, 0.61732295, 0.54763429])

In [101]:
# 16 Subtract the mean of each row of a matrix 

In [114]:
A = np.random.randint(10, size=(3,3))
print(A)
B = A.mean(axis=1, keepdims = True)
B


[[2 8 3]
 [3 2 0]
 [4 6 0]]


array([[4.33333333],
       [1.66666667],
       [3.33333333]])

In [119]:
#17 How to get the n largest values of an array
# Z = np.arange(10000)
# np.random.shuffle(Z)
# n = 5
# hint: np.argsort | np.argpartition 

arra=np.arange(10000)
arra
np.random.shuffle(arra)
newarr = np.argsort(arra)[-5:]
arra[newarr]

array([9995, 9996, 9997, 9998, 9999])

In [ ]:
# 18. Create a random 5*3 matrix and replace items that are larger than 4 by their squares ( Example:  6 --> 36)

In [1]:
import numpy as np
a = np.random.randint(25, size=(5,3))
print(a)

# result = a[a > 4] = a**2
# result
b=np.where(a, a>4, a**2)
b

[[20  5 16]
 [11 23  0]
 [ 3  8  3]
 [ 6  1 21]
 [ 3 15 15]]


array([[1, 1, 1],
       [1, 1, 2],
       [0, 1, 0],
       [1, 0, 1],
       [0, 1, 1]])